version: '2'

services:
  api:
    build: ./api
    command: npm run dev 
    mem_limit: 512mb
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "128k"
        max-file: "1"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    networks:
      - back-tier
    #depends_on:
      #- db

  #db:
    #mem_limit: 512m
    #image: percona
    #ports:
      #- "3306:3306"
    #environment:
      #MYSQL_ROOT_PASSWORD: '1005Langley'
      #MYSQL_USER: 'creative_approval_api_user'
      #MYSQL_PASSWORD: 'CRouKZ6dKbr4iZrkCB'
      #MYSQL_DATABASE: 'creative_approval'
    #logging:
      #driver: "json-file"
      #options:
        #max-size: "512k"
        #max-file: "1"
    #networks:
      #- back-tier

networks:
  back-tier:
    driver: bridge
